# Generated by Django 4.2.1 on 2023-05-26 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(default='changeme', max_length=255)),
                ('bio', models.TextField(default='I have not edited my bio yet.')),
                ('country', models.CharField(default='here', max_length=100)),
                ('city', models.CharField(default='here city', max_length=100)),
                ('profile_picture', models.ImageField(upload_to='profile_pictures')),
            ],
        ),
    ]
