# Generated by Django 4.2.1 on 2023-05-21 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_user_is_verified'),
    ]

    operations = [
        migrations.CreateModel(
            name='VerificationURL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_string', models.CharField(max_length=30)),
                ('user_id', models.IntegerField()),
            ],
        ),
    ]
