# Generated by Django 4.2.1 on 2023-05-26 00:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profile_management', '0001_initial'),
        ('authentication', '0004_verificationurl'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='has_two_factor',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='profile_management.profile'),
        ),
    ]
